---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-facts-distribution
# talk to all hosts just so we can learn about them
- hosts: 127.0.0.1
  connection: local
  tasks:
    - group_by:
        key: os_{{ ansible_distribution }}

- hosts: os_Ubuntu
  connection: local
  gather_facts: true
  vars:
    security_enable_firewalld: no
    security_rhel7_initialize_aide: yes
    security_contrib_enabled: yes
    security_rhel7_audit_failure_flag: 1
    security_ntp_servers:
      - ntp1.sirim.my
      - ntp2.sirim.my
  roles:
    - {role: update-ubuntu-ASIMP, upgrade_ubuntu_check: true, dist_upgrade_ubuntu_check: true}
    - dev-sec.ssh-hardening
#    - ansible-hardening
    - {role: lynis-ansible, lynis_use_packages: true, lynis_audit_system_linux: true}

- hosts: os_CentOS
  connection: local
  become: yes
  gather_facts: true
  vars:
    security_enable_firewalld: no
    security_rhel7_initialize_aide: yes
    security_contrib_enabled: yes
    security_rhel7_audit_failure_flag: 1
    security_ntp_servers:
      - ntp1.sirim.my
      - ntp2.sirim.my
  roles:
    - dev-sec.ssh-hardening
#    - ansible-hardening
    - {role: linuxmalaysia.lynis_ansible, lynis_use_packages: true, lynis_audit_system_linux: true}
