# Install influxdata.chrony role from the Ansible Galaxy
- src: influxdata.chrony

# Install SSH Hardening
- src: dev-sec.ssh-hardening

# Install SSH Hardening
- src: linuxmalaysia.lynis_ansible

# from GitHub OpenStack Ansible Hardening
- src: git+https://github.com/openstack/ansible-hardening
